version: "3.9"
services:
  app:
    build: .
    container_name: flask-app
    ports:
      - "8080:5000"
    environment:
      # Environment variables for DB connection
      DB_HOST: db
      DB_NAME: mensajesdb
      DB_USER: admin
      DB_PASSWORD: admin123
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      # PostgreSQL default configuration
      POSTGRES_DB: mensajesdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  db_data:
